# HOUSE PRODUCT AND CUSTOMER DATA

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
product = pd.read_csv("product.csv")
product

,ID,Building,Year of sale,Month of sale,Type of property,Property #,Area (ft.),Price,Status
0,1030,1,2005.0,11.0,Apartment,30,743.09,246172.68,Sold
1,1029,1,2005.0,10.0,Apartment,29,756.21,246331.90,Sold
2,2002,2,2007.0,7.0,Apartment,2,587.28,209280.91,Sold
3,2031,2,2007.0,12.0,Apartment,31,1604.75,452667.01,Sold
4,1049,1,2004.0,11.0,Apartment,49,1375.45,467083.31,Sold
5,3011,3,2007.0,9.0,Apartment,11,675.19,203491.85,Sold
6,3026,3,2007.0,9.0,Apartment,26,670.89,212520.83,Sold
7,3023,3,2008.0,1.0,Apartment,23,720.81,198591.85,Sold
8,1031,1,2006.0,6.0,Apartment,31,782.25,265467.68,Sold
9,4023,4,2006.0,3.0,Apartment,23,794.52,235633.26,Sold
10,1036,1,2004.0,10.0,Apartment,36,1160.36,317473.86,Sold
11,1046,1,2006.0,8.0,Apartment,46,1942.50,503790.23,Sold
12,4035,4,2007.0,10.0,Apartment,35,794.52,217786.38,Sold
13,2036,2,2006.0,11.0,Apartment,36,1109.25,460001.26,Sold
14,2056,2,2007.0,4.0,Apartment,56,1400.95,460001.26,Sold
15,1047,1,2007.0,12.0,Apartment,47,1479.72,448134.27,Sold
16,5051,5,2006.0,3.0,Apartment,51,790.54,249591.99,Sold
17,2007,2,2006.0,8.0,Apartment,7,723.93,196142.19,Sold
18,3020,3,2007.0,4.0,Apartment,20,781.07,258572.48,Sold
19,3029,3,2007.0,4.0,Apartment,29,1127.76,310831.21,Sold
20,3015,3,2006.0,10.0,Apartment,15,720.70,207281.59,Sold
21,2004,2,2006.0,12.0,Apartment,4,649.69,168834.04,Sold
22,2006,2,2006.0,12.0,Apartment,6,1307.45,396973.83,Sold
23,5013,5,2007.0,9.0,Apartment,13,618.38,188743.11,Sold
24,1026,1,2005.0,3.0,Apartment,26,625.80,179674.08,Sold
25,2054,2,2006.0,6.0,Apartment,54,1203.29,306363.64,Sold
26,3033,3,2007.0,9.0,Apartment,33,670.89,200300.63,Sold
27,1025,1,2005.0,3.0,Apartment,25,1434.09,382041.13,Sold
28,3027,3,2006.0,8.0,Apartment,27,781.07,245572.79,Sold
29,3031,3,2007.0,3.0,Apartment,31,1596.35,407214.29,Sold
...,...,...,...,...,...,...,...,...,...
237,5004,5,NaN,NaN,Apartment,4,798.50,250415.38,NaN
238,5005,5,NaN,NaN,Apartment,5,798.50,219252.89,NaN
239,5006,5,NaN,NaN,Apartment,6,1058.25,264011.70,NaN
240,5007,5,NaN,NaN,Apartment,7,618.16,211406.87,NaN
241,5008,5,NaN,NaN,Apartment,8,1273.88,396330.29,NaN
242,5009,5,NaN,NaN,Apartment,9,798.50,227072.88,NaN
243,5010,5,NaN,NaN,Apartment,10,798.50,276323.87,NaN
244,5011,5,NaN,NaN,Apartment,11,798.50,230943.38,NaN
245,5012,5,NaN,NaN,Apartment,12,1058.25,315382.11,NaN
246,5014,5,NaN,NaN,Apartment,14,1273.55,372016.56,NaN
247,5015,5,NaN,NaN,Apartment,15,798.50,237680.88,NaN
248,5016,5,NaN,NaN,Apartment,16,798.50,234032.88,NaN
249,5017,5,NaN,NaN,Apartment,17,798.28,273165.58,NaN
250,5018,5,NaN,NaN,Apartment,18,1057.92,271227.49,NaN
251,5020,5,NaN,NaN,Apartment,20,1273.55,349865.22,NaN
252,5025,5,NaN,NaN,Apartment,25,618.16,199730.73,NaN
253,5026,5,NaN,NaN,Apartment,26,1273.55,338482.45,NaN
254,5030,5,NaN,NaN,Apartment,30,1057.92,351304.58,NaN
255,5032,5,NaN,NaN,Apartment,32,1273.55,338472.13,NaN
256,5034,5,NaN,NaN,Apartment,34,798.28,212916.36,NaN
257,5036,5,NaN,NaN,Apartment,36,1057.92,308660.80,NaN
258,5037,5,NaN,NaN,Apartment,37,606.33,147343.69,NaN
259,5038,5,NaN,NaN,Apartment,38,1273.55,448574.67,NaN
260,5041,5,NaN,NaN,Apartment,41,798.28,255337.90,NaN
261,5043,5,NaN,NaN,Apartment,43,598.58,175773.59,NaN
262,5044,5,NaN,NaN,Apartment,44,1238.58,322610.74,NaN
263,5047,5,NaN,NaN,Apartment,47,794.52,279191.26,NaN
264,5048,5,NaN,NaN,Apartment,48,1013.27,287996.53,NaN
265,5050,5,NaN,NaN,Apartment,50,1074.71,365868.78,NaN
266,5051,5,NaN,NaN,Apartment,51,789.25,199216.40,NaN

In [3]:
customer = pd.read_csv("customer.csv")
customer

,Customer ID,Entity,Name,Surname,Age at time of purchase,Interval,Y,M,D,Gender,Country,State,Purpose,Deal satisfaction,Mortgage,Source
0,C0028,Individual,Madalyn,Mercer,19.00,18-25,1986.0,6.0,21.0,F,USA,California,Home,5.0,No,Website
1,C0027,Individual,Lara,Carrillo,22.00,18-25,1983.0,2.0,24.0,F,USA,California,Home,5.0,No,Website
2,C0112,Individual,Donavan,Flowers,22.00,18-25,1985.0,12.0,27.0,M,USA,California,Home,1.0,Yes,Client
3,C0160,Individual,Darien,Dorsey,22.00,18-25,1985.0,12.0,27.0,M,USA,California,Investment,3.0,Yes,Website
4,C0014,Individual,Alessandra,Perry,25.00,18-25,1979.0,5.0,15.0,F,USA,California,Home,4.0,No,Agency
5,C0125,Individual,Kaitlin,Owen,26.00,26-35,1981.0,12.0,26.0,F,USA,Virginia,Investment,5.0,No,Client
6,C0125,Individual,Kaitlin,Owen,26.00,26-35,1981.0,12.0,26.0,F,USA,Virginia,Investment,5.0,No,Agency
7,C0166,Individual,Terry,Forbes,26.00,26-35,1982.0,5.0,27.0,M,USA,California,Home,5.0,No,Client
8,C0034,Individual,Kole,Shannon,27.00,26-35,1979.0,6.0,27.0,M,USA,Arizona,Home,2.0,Yes,Website
9,C0170,Individual,Emmy,Singh,27.00,26-35,1979.0,12.0,3.0,F,USA,Virginia,Investment,3.0,Yes,Agency
10,C0009,Individual,Arabella,Ferrell,28.00,26-35,1976.0,8.0,17.0,F,USA,Oregon,Home,1.0,No,Agency
11,C0041,Individual,Christian,Costa,26.00,26-35,1980.0,9.0,14.0,M,USA,California,Home,5.0,No,Website
12,C0057,Individual,Michelle,Cameron,29.00,26-35,1978.0,6.0,4.0,F,USA,Nevada,Home,3.0,Yes,Website
13,C0061,Individual,Enrique,Cardenas,29.00,26-35,1977.0,6.0,10.0,M,USA,California,Home,2.0,No,Website
14,C0089,Individual,Amanda,Simon,29.00,26-35,1978.0,12.0,3.0,F,USA,California,Home,5.0,No,Agency
15,C0159,Individual,Kamden,Stewart,29.00,26-35,1978.0,9.0,14.0,M,USA,California,Home,5.0,No,Website
16,C0171,Individual,Skylar,Buchanan,29.00,26-35,1977.0,12.0,25.0,M,USA,Nevada,Home,4.0,Yes,Website
17,C0042,Individual,Michael,Juarez,30.00,26-35,1976.0,12.0,25.0,M,USA,Colorado,Home,4.0,Yes,Agency
18,C0093,Individual,Antonio,Porter,30.00,26-35,1977.0,1.0,8.0,M,USA,Arizona,Home,5.0,No,Client
19,C0093,Individual,Antonio,Porter,30.00,26-35,1977.0,1.0,8.0,M,USA,Arizona,Home,3.0,No,Client
20,C0051,Individual,Conner,Huff,31.00,26-35,1975.0,3.0,22.0,M,USA,Nevada,Home,5.0,No,Website
21,C0064,Individual,Joaquin,Mullins,31.00,26-35,1975.0,10.0,5.0,M,USA,California,Investment,5.0,No,Agency
22,C0064,Individual,Joaquin,Mullins,31.00,26-35,1975.0,10.0,5.0,M,USA,California,Investment,5.0,No,Agency
23,C0128,Individual,Kyla,Walker,31.00,26-35,1976.0,2.0,26.0,F,USA,Colorado,Home,4.0,Yes,Agency
24,C0019,Individual,Victor,Jensen,32.00,26-35,1973.0,9.0,1.0,M,USA,California,Home,4.0,No,Website
25,C0037,Individual,Tyler,Carr,32.00,26-35,1974.0,3.0,27.0,M,USA,California,Home,5.0,Yes,Client
26,C0127,Individual,Maia,Chandler,32.00,26-35,1975.0,8.0,12.0,F,USA,Utah,Home,1.0,Yes,Website
27,C0018,Individual,Rodrigo,Ramirez,33.00,26-35,1972.0,3.0,26.0,M,USA,California,Home,1.0,No,Agency
28,C0040,Individual,Gianni,Fritz,33.00,26-35,1973.0,9.0,15.0,M,USA,California,Home,3.0,No,Website
29,C0080,Individual,Janelle,Espinoza,33.00,26-35,1974.0,12.0,25.0,F,USA,California,Investment,4.0,No,Client
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,C0126,Individual,Crystal,Wyatt,67.00,65+,1939.0,6.0,30.0,F,USA,Oregon,Investment,3.0,Yes,Website
167,C0106,Individual,Ruben,Melton,68.00,65+,1939.0,3.0,5.0,M,USA,Utah,Investment,2.0,No,Agency
168,C0115,Individual,Issac,Edwards,69.00,65+,1938.0,10.0,29.0,M,USA,California,Home,5.0,No,Website
169,C0115,Individual,Issac,Edwards,69.00,65+,1938.0,10.0,29.0,M,USA,California,Home,5.0,No,Website
170,C0129,Individual,Jesus,Obrien,69.00,65+,1938.0,6.0,9.0,M,USA,Oregon,Investment,3.0,No,Website
171,C0129,Individual,Jesus,Obrien,69.00,65+,1938.0,6.0,9.0,M,USA,Oregon,Investment,3.0,No,Website
172,C0103,Individual,Jamal,Mueller,71.00,65+,1936.0,8.0,13.0,M,USA,Oregon,Investment,2.0,No,Website
173,C0103,Individual,Jamal,Mueller,71.00,65+,1936.0,8.0,13.0,M,USA,Oregon,Investment,2.0,No,Website
174,C0021,Individual,Kaylin,Villarreal,73.00,65+,1932.0,6.0,13.0,F,Russia,NaN,Investment,3.0,No,Website
175,C0148,Individual,Myah,Roman,73.00,65+,1933.0,5.0,5.0,F,USA,California,Investment,5.0,Yes,Agency
176,C0172,Individual,Henry,Kennedy,73.00,65+,1933.0,6.0,8.0,M,USA,California,Home,4.0,Yes,Agency
177,C0104,Individual,Diana,Hunt,76.00,65+,1931.0,2.0,13.0,F,USA,Arizona,Home,3.0,No,Website
178,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,C0001,Firm,Kamd,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Agency
180,C0012,Firm,Bridger CAL,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,Nevada,Investment,5.0,No,Website
181,C0012,Firm,Bridger CAL,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,Nevada,Investment,4.0,No,Website
182,C0025,Firm,Abdiel,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,Nevada,Investment,5.0,Yes,Website
183,C0029,Firm,Kenyon,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,Nevada,Investment,1.0,Yes,Website
184,C0029,Firm,Kenyon,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,1.0,Yes,Website
185,C0055,Firm,Kylax,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
186,C0121,Firm,Esther,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Home,3.0,Yes,Website
187,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
188,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
189,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
190,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
191,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
192,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
193,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
194,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website
195,C0174,Firm,Marleez,Co,NaN,NaN,NaN,NaN,NaN,NaN,USA,California,Investment,5.0,No,Website

--------------------------------

<b>TASK 01</b>

In [4]:
customer["Customer ID"].dtype

dtype('O')

In [5]:
customer["Mortgage"].dtype

dtype('O')

In [6]:
product["Year of sale"].dtype

dtype('float64')